### ISSUE TITLE
Corrections and bugs

### ISSUE THREAD

**Issue by pitzzz** [cmda-the-lab/study-guide-frontend-input#21] opened 2018-12-18 15:33 UTC
1. When clicking "verder" on a section it should scroll to the top of the section
2. Short description should be 350 characters
3. If I select vak, and vak is always 3 points, why do I need to type the amount of points?
4. I find the werkvormen question unclear. The descriptions are to short (for me at least). Perhaps it's a language barrier?
5. In the studiemateriaal questions we should find a way to collect links. Even if it's a book there's always a link. This will come super handy in the future.
6. Beroepsproducten should be a search field where I can add my own items or select them if they already exist.
7. When missing info it should clearly state what question is missing
8. 
9. Beroepsproducten - I still find these weird. Curious to see what other teachers make out of this list. That's more of a discussion with the cur cum than a bug though
10.

**Comment by Razpudding** [comment] 2018-12-18 15:43
1\. Agree, issue is already listed [here](https://github.com/cmda-the-lab/study-guide-frontend-input/issues/19)
3\. Might be dangerous to take out in case an edge case arises. They'd need us to fix it while taking away the option only helps marginally.
4\. Agreed, also found it confusing
5\. This is already listed as an issue.
6\. hmm maybe. I think the problem is people use different words to describe the same thing. That's a bigger issue than having to scroll down the list. So ideally some descriptions would show up like with the cards?
7\. That would be a nice enhancement (although the result is the same, you still have to scroll up. an alternative would be to auto scroll to the first question not filled in)

**Comment by wooorm** [comment] 2018-12-18 16:44
> 3\. If I select vak, and vak is always 3 points, why do I need to type the amount of points?

It’s not always three points. For example, “Data week” is 2 points. Altho I dunno if it’s a “course” or a “project”, but still, there are edge cases. **Also: ProTip™ you can click on “three points”!**

> 4\. I find the werkvormen question unclear. The descriptions are to short (for me at least). Perhaps it's a language barrier?

Really? Well, it’s really vague. It’s a weird question because it affects what rooms you get and how much hours/money you get. So 🤷‍♂️

> 5\. In the studiemateriaal questions we should find a way to collect links. Even if it's a book there's always a link. This will come super handy in the future.

Yep, that’s GH-11.

> 6\. Beroepsproducten should be a search field where I can add my own items or select them if they already exist.

I believe I asked David for a list of descriptions!

> 7\. When missing info it should clearly state what question is missing

Some possible solutions:

* List of “wrong” answers, with click-scroll buttons to go to them (only works for the first on you have wrong to, because then you’re away from the list)
* Immediately show a good answer big and green if it’s OK, that way you know you can go on to the next
* Some fixed toolbar where you can navigate to the first/last/prev/next wrong answer

**Comment by Razpudding** [comment] 2018-12-18 17:13
> List of “wrong” answers, with click-scroll buttons to go to them (only works for the first on you have wrong to, because then you’re away from the list)
Immediately show a good answer big and green if it’s OK, that way you know you can go on to the next
Some fixed toolbar where you can navigate to the first/last/prev/next wrong answer

I hate the second option. Firstsounds alright but I like my solution better.

**Comment by wooorm** [comment] 2019-03-05 03:29
These are all fixed in the cmd-curriculum-form@next!

**Closed as completed by wooorm** 2019-03-05 03:29 UTC
